export const mocked = [
    {
      id: 1,
      row: 'I',
      seat: 1,
      taken: true,
    },
      {
      id: 2,
      row: 'I',
      seat: 2,
      taken: true,
    },
      {
      id: 3,
      row: 'I',
      seat: 3,
      taken: true,
    },
      {
      id: 4,
      row: 'I',
      seat: 4,
      taken: true,
    },
      {
      id: 5,
      row: 'I',
      seat: 5,
      taken: true,
    },
      {
      id: 6,
      row: 'II',
      seat: 6,
      taken: true,
    },  {
      id: 7,
      row: 'II',
      seat: 7,
      taken: false,
    },  {
      id: 8,
      row: 'II',
      seat: 8,
      taken: true,
    },  {
      id: 9,
      row: 'II',
      seat: 9,
      taken: true,
    },  {
      id: 10,
      row: 'II',
      seat: 10,
      taken: true,
    }, {
        id: 1,
        row: 'II',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'III',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'IV',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'V',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'VI',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'VII',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'VII',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'IX',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      }, {
        id: 1,
        row: 'X',
        seat: 1,
        taken: true,
      },
        {
        id: 2,
        row: 'I',
        seat: 2,
        taken: true,
      },
        {
        id: 3,
        row: 'I',
        seat: 3,
        taken: true,
      },
        {
        id: 4,
        row: 'I',
        seat: 4,
        taken: true,
      },
        {
        id: 5,
        row: 'I',
        seat: 5,
        taken: true,
      },
        {
        id: 6,
        row: 'II',
        seat: 6,
        taken: true,
      },  {
        id: 7,
        row: 'II',
        seat: 7,
        taken: false,
      },  {
        id: 8,
        row: 'II',
        seat: 8,
        taken: true,
      },  {
        id: 9,
        row: 'II',
        seat: 9,
        taken: true,
      },  {
        id: 10,
        row: 'II',
        seat: 10,
        taken: true,
      },
  ]

  export const numberOfSeats = 100;